### PR TITLE
Add validate_id, micro_uri range, etc

### PR DESCRIPTION
**Pull request by matthewd0123**
* Add validation for id property in uattributes
* Check ranges for Micro URI and add missing test coverage
* Check UAuthority and UResource names are not blank

These changes follow the changes made in up-java since 1.5.7 was released.

### CODE REVIEW

**Comment by matthewd0123** [comment]
#29

**Review by neelam-kushwah — APPROVED** [review]
Most of the changes are due to formatting. Other changes related to ID validation and micro URI range look good to me.

**Comment by neelam-kushwah** [comment]
@matthewd0123 Can you bump the version to 0.1.3-dev

**Comment by matthewd0123** [comment]
> @matthewd0123 Can you bump the version to 0.1.3-dev

done

**Pull request merged**
